config/routes.rb
BackchannelV1::Application.routes.draw do
  resources :post_votes

  resources :comment_votes

  resources :post_comments

  get 'typical_user' => 'typical_user#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get "typical_user/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  resources :users

  get "postpool/index"
  resources :posts

  resources :categories

    root 'postpool#index', as: 'postpool'

  

end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :post_comment
  belongs_to :user
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  before_action :set_comment_vote, only: [:show, :edit, :update, :destroy]

  # GET /comment_votes
  # GET /comment_votes.json
  def index
    @comment_votes = CommentVote.all
  end

  # GET /comment_votes/1
  # GET /comment_votes/1.json
  def show
  end

  # GET /comment_votes/new
  def new
    @comment_vote = CommentVote.new
  end

  # GET /comment_votes/1/edit
  def edit
  end

  # POST /comment_votes
  # POST /comment_votes.json
  def create
    @comment_vote = CommentVote.new(comment_vote_params)
    @comment_votes = CommentVote.where(:post_comment_id => @comment_vote.post_comment_id)
    @post_comments = PostComment.all
      if @comment_votes.find_by(voter_id: session[:user_id]) != nil
        flash[:notice] = 'Cannot vote anymore!'
        redirect_to(@comment_vote.post_comment.post)
      elsif @post_comments.find_by(id: @comment_vote.post_comment_id).commentor_id == session[:user_id]
        flash[:notice] = "Cannot vote the comment created by you!"
        redirect_to(@comment_vote.post_comment.post)
      else
        @comment_vote.save
        flash[:notice] = 'Successfully voted!'
        redirect_to(@comment_vote.post_comment.post)
    end
  end

  # PATCH/PUT /comment_votes/1
  # PATCH/PUT /comment_votes/1.json
  def update
    respond_to do |format|
      if @comment_vote.update(comment_vote_params)
        format.html { redirect_to @comment_vote, notice: 'Comment vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_votes/1
  # DELETE /comment_votes/1.json
  def destroy
    @comment_vote.destroy
    respond_to do |format|
      format.html { redirect_to comment_votes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment_vote
      @comment_vote = CommentVote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_vote_params
      params.require(:comment_vote).permit(:voter_id, :quantity, :post_comment_id, :user_id)
    end
end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
end

app/views/comment_votes/_form.html.erb
<%= form_for(@comment_vote) do |f| %>
  <% if @comment_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment_vote.errors.count, "error") %> prohibited this comment_vote from being saved:</h2>

      <ul>
      <% @comment_vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voter_id %><br>
    <%= f.number_field :voter_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :post_comment %><br>
    <%= f.text_field :post_comment %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comment_votes/edit.html.erb
<h1>Editing comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment_vote %> |
<%= link_to 'Back', comment_votes_path %>

app/views/comment_votes/index.html.erb
<h1>Listing comment_votes</h1>

<table>
  <thead>
    <tr>
      <th>Voter</th>
      <th>Quantity</th>
      <th>Post comment</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_votes.each do |comment_vote| %>
      <tr>
        <td><%= comment_vote.voter_id %></td>
        <td><%= comment_vote.quantity %></td>
        <td><%= comment_vote.post_comment %></td>
        <td><%= comment_vote.user %></td>
        <td><%= link_to 'Show', comment_vote %></td>
        <td><%= link_to 'Edit', edit_comment_vote_path(comment_vote) %></td>
        <td><%= link_to 'Destroy', comment_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment vote', new_comment_vote_path %>

app/views/comment_votes/new.html.erb
<h1>New comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', comment_votes_path %>

app/views/comment_votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voter:</strong>
  <%= @comment_vote.voter_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @comment_vote.quantity %>
</p>

<p>
  <strong>Post comment:</strong>
  <%= @comment_vote.post_comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment_vote.user %>
</p>

<%= link_to 'Edit', edit_comment_vote_path(@comment_vote) %> |
<%= link_to 'Back', comment_votes_path %>